// House (decant-brand) logos, theme-aware. Map of house name -> { dark, light }
// committed logo paths (public/img/houses/...), generated by scripts/house_logos.py.
// `dark` = white logo for the dark UI; `light` = dark logo for light mode.
import data from "@/data/generated/house_logos.json";

export interface HouseLogo {
  dark: string;
  light: string;
}

const LOGOS = data as Record<string, HouseLogo>;

// Houses whose logo is a mark/monogram rather than a wordmark spelling the name.
// For these we still show the logo but KEEP the text label beside it.
const NON_WORDMARK = new Set<string>(["Pristine Aromas"]);

export function houseLogo(name: string | undefined | null): HouseLogo | null {
  return name ? LOGOS[name] ?? null : null;
}

// A wordmark logo already shows the house name, so its text label can be dropped.
// A mark/monogram does not, so keep the text.
export function houseLogoIsWordmark(name: string | undefined | null): boolean {
  return name ? !NON_WORDMARK.has(name) : false;
}
