// Canonical Fragrantica reference maps (generated by scripts/build_reference_maps.py).
import accordColorsData from "@/data/generated/accord_colors.json";
import noteImagesData from "@/data/generated/note_images.json";

const ACCORD_COLORS = accordColorsData as Record<string, string>;
const NOTE_IMAGES = noteImagesData as Record<string, string>;

export function accordColor(name: string): string | null {
  return ACCORD_COLORS[name.trim().toLowerCase()] ?? null;
}

export function noteImage(name: string): string | null {
  return NOTE_IMAGES[name.trim().toLowerCase()] ?? null;
}
