#!/usr/bin/env python3
"""House (decant-brand) logos, theme-aware. For each house provide a WHITE logo
(`dark`, shown on the dark UI) and a DARK logo (`light`, shown in light mode). Logos
are usually already transparent PNGs, so we just trim — no ML removal.

  HOUSE_LOGOS = { "House": {"dark": <white-logo-url>, "light": <dark-logo-url>} }
  (a bare string is used for both themes.)

Outputs public/img/houses/<slug>[-light].png + data/generated/house_logos.json
({ house: {"dark": path, "light": path} }), read by lib/houseLogos.ts.

  python3 scripts/house_logos.py
"""
import io
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUTDIR = ROOT / "public" / "img" / "houses"
MAP = ROOT / "data" / "generated" / "house_logos.json"
OUTDIR.mkdir(parents=True, exist_ok=True)

# Provide whichever theme version(s) exist; a MISSING one is auto-generated by
# inverting the other (good for monochrome wordmarks).
HOUSE_LOGOS = {
    "Arome": {
        "dark": "https://arome.pk/cdn/shop/files/Asset-1_4x_copy.png?v=1680483379&width=800",   # white
        "light": "https://arome.pk/cdn/shop/files/arome.png?v=1680483374&width=800",             # black
    },
    "Scent It": {
        # only a black logo exists -> use for light, auto-invert for dark
        "light": "https://scentit.com.pk/wp-content/uploads/2025/08/scentit-cropped-removebg-preview.png.webp",
    },
    "Twisty Scents": {  # white wordmark
        "dark": "https://twistyscents.pk/cdn/shop/files/TTT-01.png?width=900",
    },
    "Sesky": {  # dark wordmark
        "light": "https://sesky.pk/wp-content/uploads/2023/10/logo_sesky.png",
    },
    "Enchante": {  # black-on-white JPG -> white removed on load
        "light": "https://www.enchante.pk/cdn/shop/files/Enchante.jpg?width=900",
    },
    "Nioi Sentirbon": {  # teal "Sentir Bon Fragrances" wordmark (dark ink)
        "light": "https://sentirbon.pk/cdn/shop/files/LOGO_123_b61c4c0a-3c58-45b1-98c0-fff3b2b28133-removebg-preview.png?v=1664696617&width=800",
    },
    "Pristine Aromas": {  # cursive monogram (their only mark; black on transparent)
        "light": "https://pristinearomas.pk/cdn/shop/files/icon.png?v=1771254775&width=800",
    },
    "Scent N Stories": {  # white script wordmark + gold quill
        "dark": "https://scentsnstories.pk/cdn/shop/files/SNS_Logo_For_Web_NEW.webp?v=1765471214&width=800",
    },
    # ── Middle Eastern houses (each promoted to their own group) ──────────
    "Afnan": {  # white wordmark
        "dark": "https://afnan.com/cdn/shop/files/white_afnan_logo.png?v=1727709400&width=2000",
    },
    "Armaf": {  # black wordmark on transparent
        "light": "https://armaf.com/cdn/shop/files/Armaf_Black_Logo-removebg-preview_1.png?v=1765219631&width=500",
    },
    "Rasasi": {  # colored (blue) wordmark — use as-is for both themes, no inversion
        "dark": "https://rasasi.com/img/logo.png",
        "light": "https://rasasi.com/img/logo.png",
    },
    "Lattafa": {  # colored (gold + blue) mark — use as-is for both themes
        "dark": "https://lattafapakistan.com/cdn/shop/files/lattaffa-logo.avif?v=1751564644&width=1500",
        "light": "https://lattafapakistan.com/cdn/shop/files/lattaffa-logo.avif?v=1751564644&width=1500",
    },
    "Ahmed Al-Maghrabi": {  # colored (blue) mark — use as-is for both themes
        "dark": "https://ae.ahmedalmaghribi.com/assets/images/logo/Desktop.svg",
        "light": "https://ae.ahmedalmaghribi.com/assets/images/logo/Desktop.svg",
    },
    "Maison Alhambra": {  # black stag crest on white — white_to_alpha turns white transparent
        "light": "https://maisonalhambraperfume.com/wp-content/uploads/2025/01/cropped-473676545_609461084876488_11402663045625254_n.jpg",
    },
    "J.": {  # dark mark SVG — auto-inverts for dark theme
        "light": "https://www.junaidjamshed.com/cdn/shop/files/logo_black_-_wania_saleem_453f84ad-f61b-4978-ab3d-785cf12ce04c.svg?v=1768559418",
    },
}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def fetch(url):
    r = subprocess.run(["/usr/bin/curl", "-sL", url], capture_output=True)
    return r.stdout if r.returncode == 0 and len(r.stdout) > 600 else None


from PIL import ImageOps


def name_for(base, theme):
    return f"{base}.png" if theme == "dark" else f"{base}-light.png"


def white_to_alpha(im):
    """For an opaque (e.g. JPG) logo on a white background: derive alpha from
    darkness so the white bg becomes transparent and dark ink stays. Anti-aliased."""
    import numpy as np
    a = np.array(im)
    a[:, :, 3] = 255 - a[:, :, :3].min(axis=2)
    return Image.fromarray(a, "RGBA")


def _magick_to_png(raw, ext):
    """Rasterize SVG or AVIF to PNG bytes via ImageMagick 7."""
    with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as f:
        f.write(raw)
        tmp = f.name
    try:
        r = subprocess.run(
            ["magick", tmp, "-background", "none", "png:-"],
            capture_output=True,
        )
        return r.stdout if r.returncode == 0 and len(r.stdout) > 100 else None
    finally:
        os.unlink(tmp)


def load(url):
    raw = fetch(url)
    if not raw:
        return None
    # SVG: PIL can't parse; rasterise with ImageMagick
    is_svg = raw.lstrip()[:4] in (b"<svg", b"<?xm") or b"<svg" in raw[:500]
    # AVIF: Pillow doesn't support AVIF on this system
    is_avif = not is_svg and len(raw) > 12 and raw[4:8] == b"ftyp"
    if is_svg or is_avif:
        raw = _magick_to_png(raw, ".svg" if is_svg else ".avif")
        if not raw:
            return None
    try:
        im = Image.open(io.BytesIO(raw)).convert("RGBA")
    except Exception as e:
        print(f"  PIL open failed: {e}")
        return None
    import numpy as np
    if (np.array(im)[:, :, 3] > 250).mean() > 0.95:  # no real transparency (JPG)
        im = white_to_alpha(im)
    bb = im.getbbox()
    return im.crop(bb) if bb else im


def invert_rgb(im):
    """Invert colour, keep alpha — turns a black wordmark white and vice-versa."""
    r, g, b, a = im.split()
    rgb = ImageOps.invert(Image.merge("RGB", (r, g, b)))
    return Image.merge("RGBA", (*rgb.split(), a))


def main():
    out_map = json.loads(MAP.read_text()) if MAP.exists() else {}
    for house, val in HOUSE_LOGOS.items():
        urls = val if isinstance(val, dict) else {"dark": val, "light": val}
        base = slug(house)
        imgs = {t: load(u) for t, u in urls.items() if u}
        imgs = {t: im for t, im in imgs.items() if im is not None}
        if not imgs:
            print(f"  ✗ {house}: no logo downloaded")
            continue
        # generate the missing theme by inverting the available one
        for theme in ("dark", "light"):
            if theme not in imgs:
                src = imgs["dark" if "dark" in imgs else "light"]
                imgs[theme] = invert_rgb(src)
        entry = {}
        for theme in ("dark", "light"):
            name = name_for(base, theme)
            imgs[theme].save(OUTDIR / name)
            entry[theme] = f"/img/houses/{name}"
            print(f"  ✓ {house} [{theme}] -> {name} ({imgs[theme].size[0]}x{imgs[theme].size[1]})")
        out_map[house] = entry
    MAP.write_text(json.dumps(out_map, indent=2, ensure_ascii=False))
    print(f"house_logos.json: {len(out_map)} houses")


if __name__ == "__main__":
    main()
